services:
  app:
    build: ./app
    init: true
    env_file: ./app/.env
    environment:
      NODE_ENV: development
      PAI_CATALOG_DIR: /var/app/pai-catalogs
    volumes:
      - ./data/pai-catalogs:/var/app/pai-catalogs:ro
      - ./data/pai-images:/app/build/client/pai-images:ro
    ports:
      - "3000:3000"
